version: '3.7'

services:
  opensearch:
    image: opensearchproject/opensearch:2.14.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data:Z
    ports:
      - "9200:9200"
    networks:
      - opensearch-net

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.14.0
    container_name: dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    volumes:
      - dashboards-data:/usr/share/opensearch-dashboards/data:Z
    ports:
      - "5601:5601"
    depends_on:
      - opensearch
    networks:
      - opensearch-net

  scheduler:
    image: scheduler-app:latest
    container_name: scheduler
    volumes:
      - scheduler-data:/usr/share/scheduler:Z
    depends_on:
      - opensearch
      - dashboards
    networks:
      - opensearch-net

volumes:
  opensearch-data:
    driver: local
    driver_opts:
      type: none
      device: /data/opensearch
      o: bind

  dashboards-data:
    driver: local
    driver_opts:
      type: none
      device: /data/dashboards
      o: bind

  scheduler-data:
    driver: local
    driver_opts:
      type: none
      device: /data/scheduler
      o: bind

networks:
  opensearch-net:
    external: false
